name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        environment: common
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        environment: common
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lionpkh/friday-bot:latest
      -
        name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        environment: deploy
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            docker kill friday-bot
            docker rm friday-bot
            docker run -d --privileged --name friday-bot -v /home/petr/Friday.db:/app/Friday.db:rw -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -e TELEGRAM_API_KEY=${{ secrets.TELEGRAM_API_KEY }} --restart always lionpkh/friday-bot:latest